name: wg-easy

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    env_file: .env
    environment:
      - LANG=en
      - WG_HOST=${WG_EASY_VPN_DOMAIN}
      - WG_PORT=${WG_EASY_VPN_PORT}
      - WG_DEFAULT_DNS=${LAB_IP}
      - WG_ALLOWED_IPS=0.0.0.0/0
      - PORT=${WG_EASY_PORT}
      - PASSWORD_HASH=${WG_EASY_PASSWORD_HASH}
    ports:
      - "${WG_EASY_VPN_PORT}:51820/udp"
      - "${WG_EASY_PORT}:51821/tcp"
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://10.42.42.42:51821"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    restart: unless-stopped

volumes:
  etc_wireguard:

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
