name: uptime-kuma

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    env_file: .env
    environment:
      - TZ=${TIMEZONE?error}
      - UMASK=0022
    ports:
      - ${UPTIME_KUMA_PORT?error}:3001
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "${UPTIME_KUMA_URL?error}"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    restart: unless-stopped